name: Lint Deployment Pipelines

on:
    pull_request:
    push:
        branches: [main, test-me-*]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint GoCD Pipelines
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3
            - uses: getsentry/action-setup-gocd-cli@2f7943ce1a380dea121fd6338a60dc9aabf8e7f1  # v1.0.1
            - name: Lint Pipelines with gocd-cli
              run: ./.github/workflows/lint-pipelines.sh

    render:
        name: Render GoCD Pipelines with Jsonnet
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3
            - uses: getsentry/action-gocd-jsonnet@v0
              with:
                  jb-install: true
                  check-for-changes: true
                  convert-to-yaml: true
                  jsonnet-dir: gocd/templates
                  generated-dir: gocd/generated-pipelines
